### ISSUE TITLE
Use of reselect library

### ISSUE THREAD

**Issue by varghesep** [orizens/echoes-player#12]
I just bought your book [Reactive Programming with Angular and ngrx](https://www.amazon.com/Reactive-Programming-Angular-ngrx-Extensions-ebook/dp/B0725RB6J1/ref=dp_kinw_strp_1). Thanks for putting together such a good book.

The official [ngrx example](https://github.com/ngrx/example-app/blob/b2aa4fe70400da223d8fe092befc38b9326945e3/src/app/reducers/index.ts) uses a library called [reselect](https://github.com/reactjs/reselect). I don't fully understand the reason behind using that library, but I think it is to prevent a trip to the server to retrieve the data if the data is already available in the ```redux store```.

Will the ```reselect``` library be useful in the echoes-player to improve performance?

**Comment by orizens** [comment]
hi @varghesep 
thanks for kind complements. 
i've the chance of looking to reselect just a little bit. 
currently i have some kind of direction of where the reselect would fit in echoesplayer. i'm not sure about improving performance. 
However, from what i can see of its features, i should cache state selections by manipulating accessors to retrieve the state.

**Comment by cgatian** [comment]
ngrx 4 now has [createSelector](https://github.com/ngrx/platform/blob/master/docs/store/selectors.md) which provides the perf benefits the OP mentions

**Comment by orizens** [comment]
@cgatian that's o the roadmap
