### ISSUE TITLE
Web app: click on the button "Save All These Tracks To A New Playlist" does nothing

### ISSUE THREAD

**Issue by tytskyi** [orizens/echoes-player#21]
In the web app http://echoesplayer.com click on the button "Save All These Tracks To A New Playlist" does nothing

**Comment by orizens** [comment]
Correct - that's not implemented yet.

**Comment by NMcDonough** [comment]
Have playlists been implemented at all yet or is it just the button that hasn't been implemented yet?

**Comment by orizens** [comment]
not applicable anymore

**Comment by orizens** [comment]
@NMcDonough  the "add video to playlist" is implemented - you can add a video to your youtube playlists
