### ISSUE TITLE
Different code for the same logic?

### ISSUE THREAD

**Issue by yehe01** [orizens/echoes-player#28]
in `playlists.component.ts`, `playSelectedPlaylist` calls `this.userPlayerService.playSelectedPlaylist(playlist);`
but
in `youtube-playlists.component.ts`, `playPlaylist` calls `this.appPlayerApi.playPlaylist(media);`

I have found any difference between playing youtube search playlist and playing user playlist. From my understanding, they both do something like queue videos to the now play list and select first video to play and maybe more. So, Is there anything i am missing?

**Comment by orizens** [comment]
hi @yehe01 
you're right - it's the same logic.
I'm moving the codebase to use the appPlayerApi as the main proxy for actions across the app.
So - eventually, the userPlayerService will use the appPlayerApi.

**Comment by yehe01** [comment]
Thanks. BTW I haven't checkout out the proxy code yet. What is the general idea of using proxy for actions?
