### ISSUE TITLE
'this.media.snippet.thumbnails.high' is optional field

### ISSUE THREAD

**Issue by yehe01** [orizens/echoes-player#29]
I came across a situation where the returned playlist doesn't not have a high field.

<img width="1240" alt="screen shot 2017-12-05 at 12 07 43 pm" src="https://user-images.githubusercontent.com/1256556/33584752-edf24864-d9b4-11e7-9b9a-a974f65da8c6.png">

There are only 49 playlists that have field "high" among the total 50.

<img width="1031" alt="screen shot 2017-12-05 at 12 01 42 pm" src="https://user-images.githubusercontent.com/1256556/33584662-88dfaf8e-d9b4-11e7-8c07-995f5486c80d.png">

On Safari the log message is more clear:

<img width="1014" alt="screen shot 2017-12-05 at 11 57 59 am" src="https://user-images.githubusercontent.com/1256556/33584684-9a008b6c-d9b4-11e7-84d3-5c8bedbcb9dd.png">

**Comment by orizens** [comment]
fixed by a323766f0c75d364de2cd5a285238f63233ac2a7
