### ISSUE TITLE
Issue On WebApp: Maximising the video, Click on it to pause/resume, Escape button does not minimise it again.

### ISSUE THREAD

**Issue by bhavya24dang** [orizens/echoes-player#41]
When I click on the video icon on bottom-left corner to maximise the video on web app, it maximises and on clicking 'ESC' button, it gets minimised again and take me back to the app. But on clicking the video for pausing/resuming it, when video is in maximised state on app, 'ESC' button does not work to minimise it. It gets stuck here, and i could not move back and forth inside the app. In that scenario, I switched to previous page. Is it an existing issue or any feature, I am unaware of?

**Comment by orizens** [comment]
that's by design.
