### ISSUE TITLE
Error during running the http-server 

### ISSUE THREAD

**Issue by BasavarajCM** [orizens/echoes-player#43]
When i tried to run ng serve, it will work properly without any issue, when i used http-server for running the application i am getting below error:

Please help me.

GET http://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js 0 ()
now-playlist.component.ts.NowPlaylistComponent.html:10 ERROR TypeError: Cannot read property 'match' of undefined
    at MediaParserService.webpackJsonp../src/app/core/services/media-parser.service.ts.MediaParserService.extractTracks (media-parser.service.ts:15)
    at NowPlaylistTrackComponent.webpackJsonp../src/app/core/components/now-playing/now-playlist/now-playlist-track.component.ts.NowPlaylistTrackComponent.extractTracks (now-playlist-track.component.ts:91)
    at NowPlaylistTrackComponent.webpackJsonp../src/app/core/components/now-playing/now-playlist/now-playlist-track.component.ts.NowPlaylistTrackComponent.ngAfterContentInit (now-playlist-track.component.ts:86)
    at callProviderLifecycles (core.js:12508)
    at callElementProvidersLifecycles (core.js:12482)
    at callLifecycleHooksChildrenFirst (core.js:12465)
    at checkAndUpdateView (core.js:13610)
    at callViewAction (core.js:13960)
    at execEmbeddedViewsAction (core.js:13918)
    at checkAndUpdateView (core.js:13607)
View_NowPlaylistComponent_1 @ now-playlist.component.ts.NowPlaylistComponent.html:10
webpackJsonp../node_modules/@angular/core/esm5/core.js.DebugContext_.logError @ core.js:14797
webpackJsonp../node_modules/@angular/core/esm5/core.js.ErrorHandler.handleError @ core.js:1497
(anonymous) @ core.js:5849
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
webpackJsonp../node_modules/@angular/core/esm5/core.js.NgZone.runOutsideAngular @ core.js:4647
webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationRef.tick @ core.js:5849
webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationRef._loadComponent @ core.js:5908
webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationRef.bootstrap @ core.js:5796
(anonymous) @ core.js:5525
webpackJsonp../node_modules/@angular/core/esm5/core.js.PlatformRef._moduleDoBootstrap @ core.js:5525
(anonymous) @ core.js:5444
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4699
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
(anonymous) @ zone.js:872
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4690
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:420
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
Promise.then (async)
scheduleMicroTask @ zone.js:578
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
onScheduleTask @ zone.js:297
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:401
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:232
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.scheduleMicroTask @ zone.js:252
scheduleResolveOrReject @ zone.js:862
ZoneAwarePromise.then @ zone.js:962
webpackJsonp../node_modules/@angular/router/esm5/router.js.RouterInitializer.appInitializer @ router.js:7166
webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationInitStatus.runInitializers @ core.js:3549
(anonymous) @ core.js:5442
_callAndReportToErrorHandler @ core.js:5614
(anonymous) @ core.js:5440
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4699
webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke @ zone.js:387
webpackJsonp../node_modules/zone.js/dist/zone.js.Zone.run @ zone.js:138
webpackJsonp../node_modules/@angular/core/esm5/core.js.NgZone.run @ core.js:4516
webpackJsonp../node_modules/@angular/core/esm5/core.js.PlatformRef.bootstrapModuleFactory @ core.js:5431
./src/main.ts @ main.ts:11
__webpack_require__ @ bootstrap 456367255ed6233fe7b3:54
0 @ main.ts:11
__webpack_require__ @ bootstrap 456367255ed6233fe7b3:54
webpackJsonpCallback @ bootstrap 456367255ed6233fe7b3:25
(anonymous) @ main.bundle.js:1
now-playlist.component.ts.NowPlaylistComponent.html:10 ERROR CONTEXT

**Comment by orizens** [comment]
hi.
http-server is not meant to be run with the dev version.
if you need the app for something else - please let me know via contact - http://orizen.com/contact
