### ISSUE TITLE
Is additional setup required?

### ISSUE THREAD

**Issue by aclaussen1** [orizens/echoes-player#49]
![screen shot 2018-08-26 at 5 46 55 pm](https://user-images.githubusercontent.com/11046216/44633372-64e8e180-a958-11e8-8783-ab064f63b859.png)

I am stuck here. I have changed the API keys in src/environments/environment.ts

Not sure what else is missing.

**Comment by orizens** [comment]
i guess you need to define the correct ip in google's console as well

**Comment by aclaussen1** [comment]
Thanks a bunch
