### ISSUE TITLE
Error: Cannot match any routes. URL Segment: 'video'

### ISSUE THREAD

**Issue by Marjani** [orizens/echoes-player#5]
Hello
Looks like you forgot to do your routing settings
file 'app.routes.ts' is empty

**Comment by orizens** [comment]
hi @Marjani 
Currently, routing is handled within each feature module.
The "/video/id" route has not been developed yet.
Thanks.

**Comment by Marjani** [comment]
you use  ` <router-outlet></router-outlet>` in app.component.html , but I can't find which component on home page? 
Excuse me, I am  beginners

**Comment by Marjani** [comment]
any answer?

**Comment by orizens** [comment]
look at "youtube-videos"
