### ISSUE TITLE
Mobile website on iPhone 8-top menu covers search results

### ISSUE THREAD

**Issue by aclaussen1** [orizens/echoes-player#50]
![6dff6620-aeba-4479-8f24-0e7893822066](https://user-images.githubusercontent.com/11046216/45004416-53d44c00-afba-11e8-93fc-f6126ce73879.png)

**Comment by aclaussen1** [comment]
Also reproduced on android blu phone

**Comment by aclaussen1** [comment]
Currently looking at this for solutions: 
https://stackoverflow.com/questions/16297238/angularjs-different-views-based-on-desktop-or-mobile

Will keep posting updates

**Comment by orizens** [comment]
currently, echoes doesn't support iphone-8 officialy, however if you @aclaussen1  have a suggestion for fixing it or pointing the root cause - that should help.
