### ISSUE TITLE
jsonp is deprecated

### ISSUE THREAD

**Issue by robeverett** [orizens/echoes-player#52]
Jsonp is deprecated in Angular Six
Now fixed

**Comment by orizens** [comment]
https://angular.io/api/common/http/HttpClient#jsonp

**Comment by robeverett** [comment]
Oh, ok, but the intellisense tells me it is deprecated when I hover my mouse over the import.

**Comment by orizens** [comment]
which file?

**Comment by robeverett** [comment]
Component file

**Comment by orizens** [comment]
i see - you're right - it's imported in echoes-player/src/app/containers/app-search/player-search/player-search.component.ts but it is unused. 
thanks.

**Comment by orizens** [comment]
removed.
