### ISSUE TITLE
Issue while Demo test application

### ISSUE THREAD

**Issue by francoisdutoit** [orizens/echoes-player#63]
Hi,

There seems to be an issue with the demo code and Augury Dev Tools Extension
Is this an issue with the app...or with the chrome extention?

See below...

[](url)
![Demo](https://user-images.githubusercontent.com/9386768/62517488-ca5f7680-b827-11e9-897a-4f4920b93bac.png)

Thanks!

**Comment by francoisdutoit** [comment]
Seems to be an issue with the extension....

Belowis a screenshot from firefox

![image](https://user-images.githubusercontent.com/9386768/62517923-ab151900-b828-11e9-9101-89f6e623f476.png)

**Comment by francoisdutoit** [comment]
...so now tried the extension with another app and it works fine...

![image](https://user-images.githubusercontent.com/9386768/62518892-cf71f500-b82a-11e9-86a4-b968f1c51caa.png)

Augury...Polyfill issue maybe?

**Comment by orizens** [comment]
looks like an issue with augury.


*Regards,Oren Farhi*
Founder at *Orizens.com* <http://orizens.com/>
Author of *Angular NgRx* <http://www.apress.com/us/book/9781484226193>*,*
Senior Front End Engineer & Consultant
*Front End Consulting Services* <http://orizens.com/services>

**Comment by francoisdutoit** [comment]
Thanks!
