### ISSUE TITLE
#UX: letter spacing and URL color might need an update

### ISSUE THREAD

**Issue by bZichett** [orizens/echoes-player#64]
I like the overall UI / card look, but I have two suggestions.

1) Rehaul either the chosen font-family, or if you want to stick with it, increase the letter-spacing since basically everything feels crammed together.  

2) The link url color is too light, and make readability a little difficult (and more so combined with the compressed letters)

---

Perhaps this may not be the same for all users since there are fallback fonts, but here is how it looks on my computer (Chromium on Linux)

![Screenshot from 2019-10-31 08-58-22](https://user-images.githubusercontent.com/7804797/67948867-fbe4a580-fbbc-11e9-8a89-695d496f8a14.png)

**Comment by orizens** [comment]
hi @bZichett 
1. sounds like a good suggestion. currently using "open sans condensed" - i'll test out "open sans" and see how it feels.
2. if that's regarding the media title - i'll consider making it bolder or using a darker color for links overall.
Thanks for the inputs 👍  keep 'em coming.

**Comment by orizens** [comment]
@bZichett echoes has been updated since. please take a look.
