### ISSUE TITLE
ChromEchoes - Not compatible with non-chromebook devices

### ISSUE THREAD

**Issue by vaidd4** [orizens/echoes-player#7]
The echoes chrome app main page is not found:
**_"404
There isn't a GitHub Pages site here."_**

The app doesn't seem to be using the `http://echoesplayer.com` url 

ref:
https://chrome.google.com/webstore/detail/echoes-player/aaenpaopfebcmdaegggjbkhaedlbbkde/support

**Comment by orizens** [comment]
hi @vaidd4 
are you sure? please update the app via chrome's settings -> extensions

**Comment by vaidd4** [comment]
Hi @orizens, yes i'm kinda sure
I'm using
`Echoes Player 2.0.0` (from chrome web store, date of last update : `12 mars 2017`)
with
`Chrome - Version 57.0.2987.133 (64-bit)`
on
`Ubuntu 16.10`

FYI, I have removed it and restarted it multiple times, restarted the browser and the computer but still showing this weird error.

**Comment by orizens** [comment]
hi @vaidd4 - the echoes chrome app is only updated for chrome books or machines with chromebook.
sos- i suggest using a tab in your browser or rather use a solution that allows to convert a webpage to a native app.

**Comment by orizens** [comment]
consider using https://github.com/jiahaog/nativefier

**Comment by vaidd4** [comment]
Thanks for your answer, I didn't knew about nativefier, seems pretty good !
I just updated the title to be more understandable.

**Comment by orizens** [comment]
closing - as this issue is platform related and not an app's issue.
